//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_AntennaObjects_dbo_Products_Product_ID", "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WindowsFormsApplication2.Product), "AntennaObjects", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WindowsFormsApplication2.AntennaObject), true)]
[assembly: EdmRelationshipAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_FinishedProducts_dbo_AntennaObjects_AntennaObject_ID", "AntennaObjects", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WindowsFormsApplication2.AntennaObject), "FinishedProducts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WindowsFormsApplication2.FinishedProduct), true)]
[assembly: EdmRelationshipAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_ReaderObjects_dbo_AntennaObjects_Antenna_ID", "AntennaObjects", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WindowsFormsApplication2.AntennaObject), "ReaderObjects", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WindowsFormsApplication2.ReaderObject), true)]
[assembly: EdmRelationshipAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_ReaderObjects_dbo_Manufacturers_Manufacturer_ID", "Manufacturers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WindowsFormsApplication2.Manufacturer), "ReaderObjects", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WindowsFormsApplication2.ReaderObject), true)]
[assembly: EdmRelationshipAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_Products_dbo_ProductTypes_Type_ID", "ProductTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WindowsFormsApplication2.ProductType), "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WindowsFormsApplication2.Product), true)]
[assembly: EdmRelationshipAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_ReaderObjects_dbo_Warehouses_Warehouse_ID", "Warehouses", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WindowsFormsApplication2.Warehouse), "ReaderObjects", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WindowsFormsApplication2.ReaderObject), true)]

#endregion

namespace WindowsFormsApplication2
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<C__MigrationHistory> C__MigrationHistory
        {
            get
            {
                if ((_C__MigrationHistory == null))
                {
                    _C__MigrationHistory = base.CreateObjectSet<C__MigrationHistory>("C__MigrationHistory");
                }
                return _C__MigrationHistory;
            }
        }
        private ObjectSet<C__MigrationHistory> _C__MigrationHistory;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AntennaObject> AntennaObjects
        {
            get
            {
                if ((_AntennaObjects == null))
                {
                    _AntennaObjects = base.CreateObjectSet<AntennaObject>("AntennaObjects");
                }
                return _AntennaObjects;
            }
        }
        private ObjectSet<AntennaObject> _AntennaObjects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FinishedProduct> FinishedProducts
        {
            get
            {
                if ((_FinishedProducts == null))
                {
                    _FinishedProducts = base.CreateObjectSet<FinishedProduct>("FinishedProducts");
                }
                return _FinishedProducts;
            }
        }
        private ObjectSet<FinishedProduct> _FinishedProducts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Manufacturer> Manufacturers
        {
            get
            {
                if ((_Manufacturers == null))
                {
                    _Manufacturers = base.CreateObjectSet<Manufacturer>("Manufacturers");
                }
                return _Manufacturers;
            }
        }
        private ObjectSet<Manufacturer> _Manufacturers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductType> ProductTypes
        {
            get
            {
                if ((_ProductTypes == null))
                {
                    _ProductTypes = base.CreateObjectSet<ProductType>("ProductTypes");
                }
                return _ProductTypes;
            }
        }
        private ObjectSet<ProductType> _ProductTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ReaderObject> ReaderObjects
        {
            get
            {
                if ((_ReaderObjects == null))
                {
                    _ReaderObjects = base.CreateObjectSet<ReaderObject>("ReaderObjects");
                }
                return _ReaderObjects;
            }
        }
        private ObjectSet<ReaderObject> _ReaderObjects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Warehouse> Warehouses
        {
            get
            {
                if ((_Warehouses == null))
                {
                    _Warehouses = base.CreateObjectSet<Warehouse>("Warehouses");
                }
                return _Warehouses;
            }
        }
        private ObjectSet<Warehouse> _Warehouses;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the C__MigrationHistory EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToC__MigrationHistory(C__MigrationHistory c__MigrationHistory)
        {
            base.AddObject("C__MigrationHistory", c__MigrationHistory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AntennaObjects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAntennaObjects(AntennaObject antennaObject)
        {
            base.AddObject("AntennaObjects", antennaObject);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FinishedProducts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFinishedProducts(FinishedProduct finishedProduct)
        {
            base.AddObject("FinishedProducts", finishedProduct);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Manufacturers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToManufacturers(Manufacturer manufacturer)
        {
            base.AddObject("Manufacturers", manufacturer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductTypes(ProductType productType)
        {
            base.AddObject("ProductTypes", productType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ReaderObjects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReaderObjects(ReaderObject readerObject)
        {
            base.AddObject("ReaderObjects", readerObject);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Warehouses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWarehouses(Warehouse warehouse)
        {
            base.AddObject("Warehouses", warehouse);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WMSwithRFID.WMScontextModel", Name="AntennaObject")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AntennaObject : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AntennaObject object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="function">Initial value of the Function property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="antennaPortNumber">Initial value of the AntennaPortNumber property.</param>
        public static AntennaObject CreateAntennaObject(global::System.Int32 id, global::System.Int32 function, global::System.DateTime dateCreated, global::System.Int32 antennaPortNumber)
        {
            AntennaObject antennaObject = new AntennaObject();
            antennaObject.ID = id;
            antennaObject.Function = function;
            antennaObject.DateCreated = dateCreated;
            antennaObject.AntennaPortNumber = antennaPortNumber;
            return antennaObject;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Function
        {
            get
            {
                return _Function;
            }
            set
            {
                OnFunctionChanging(value);
                ReportPropertyChanging("Function");
                _Function = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Function");
                OnFunctionChanged();
            }
        }
        private global::System.Int32 _Function;
        partial void OnFunctionChanging(global::System.Int32 value);
        partial void OnFunctionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AntennaPortNumber
        {
            get
            {
                return _AntennaPortNumber;
            }
            set
            {
                OnAntennaPortNumberChanging(value);
                ReportPropertyChanging("AntennaPortNumber");
                _AntennaPortNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AntennaPortNumber");
                OnAntennaPortNumberChanged();
            }
        }
        private global::System.Int32 _AntennaPortNumber;
        partial void OnAntennaPortNumberChanging(global::System.Int32 value);
        partial void OnAntennaPortNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Product_ID
        {
            get
            {
                return _Product_ID;
            }
            set
            {
                OnProduct_IDChanging(value);
                ReportPropertyChanging("Product_ID");
                _Product_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Product_ID");
                OnProduct_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Product_ID;
        partial void OnProduct_IDChanging(Nullable<global::System.Int32> value);
        partial void OnProduct_IDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_AntennaObjects_dbo_Products_Product_ID", "Products")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("WMSwithRFID.WMScontextModel.FK_dbo_AntennaObjects_dbo_Products_Product_ID", "Products").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("WMSwithRFID.WMScontextModel.FK_dbo_AntennaObjects_dbo_Products_Product_ID", "Products").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("WMSwithRFID.WMScontextModel.FK_dbo_AntennaObjects_dbo_Products_Product_ID", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("WMSwithRFID.WMScontextModel.FK_dbo_AntennaObjects_dbo_Products_Product_ID", "Products", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_FinishedProducts_dbo_AntennaObjects_AntennaObject_ID", "FinishedProducts")]
        public EntityCollection<FinishedProduct> FinishedProducts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FinishedProduct>("WMSwithRFID.WMScontextModel.FK_dbo_FinishedProducts_dbo_AntennaObjects_AntennaObject_ID", "FinishedProducts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FinishedProduct>("WMSwithRFID.WMScontextModel.FK_dbo_FinishedProducts_dbo_AntennaObjects_AntennaObject_ID", "FinishedProducts", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_ReaderObjects_dbo_AntennaObjects_Antenna_ID", "ReaderObjects")]
        public EntityCollection<ReaderObject> ReaderObjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReaderObject>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_AntennaObjects_Antenna_ID", "ReaderObjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReaderObject>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_AntennaObjects_Antenna_ID", "ReaderObjects", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WMSwithRFID.WMScontextModel", Name="C__MigrationHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class C__MigrationHistory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new C__MigrationHistory object.
        /// </summary>
        /// <param name="migrationId">Initial value of the MigrationId property.</param>
        /// <param name="contextKey">Initial value of the ContextKey property.</param>
        /// <param name="model">Initial value of the Model property.</param>
        /// <param name="productVersion">Initial value of the ProductVersion property.</param>
        public static C__MigrationHistory CreateC__MigrationHistory(global::System.String migrationId, global::System.String contextKey, global::System.Byte[] model, global::System.String productVersion)
        {
            C__MigrationHistory c__MigrationHistory = new C__MigrationHistory();
            c__MigrationHistory.MigrationId = migrationId;
            c__MigrationHistory.ContextKey = contextKey;
            c__MigrationHistory.Model = model;
            c__MigrationHistory.ProductVersion = productVersion;
            return c__MigrationHistory;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MigrationId
        {
            get
            {
                return _MigrationId;
            }
            set
            {
                if (_MigrationId != value)
                {
                    OnMigrationIdChanging(value);
                    ReportPropertyChanging("MigrationId");
                    _MigrationId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MigrationId");
                    OnMigrationIdChanged();
                }
            }
        }
        private global::System.String _MigrationId;
        partial void OnMigrationIdChanging(global::System.String value);
        partial void OnMigrationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ContextKey
        {
            get
            {
                return _ContextKey;
            }
            set
            {
                if (_ContextKey != value)
                {
                    OnContextKeyChanging(value);
                    ReportPropertyChanging("ContextKey");
                    _ContextKey = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ContextKey");
                    OnContextKeyChanged();
                }
            }
        }
        private global::System.String _ContextKey;
        partial void OnContextKeyChanging(global::System.String value);
        partial void OnContextKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Model
        {
            get
            {
                return StructuralObject.GetValidValue(_Model);
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.Byte[] _Model;
        partial void OnModelChanging(global::System.Byte[] value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductVersion
        {
            get
            {
                return _ProductVersion;
            }
            set
            {
                OnProductVersionChanging(value);
                ReportPropertyChanging("ProductVersion");
                _ProductVersion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductVersion");
                OnProductVersionChanged();
            }
        }
        private global::System.String _ProductVersion;
        partial void OnProductVersionChanging(global::System.String value);
        partial void OnProductVersionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WMSwithRFID.WMScontextModel", Name="FinishedProduct")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FinishedProduct : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FinishedProduct object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="dateManufactured">Initial value of the DateManufactured property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static FinishedProduct CreateFinishedProduct(global::System.Int32 id, global::System.DateTime dateManufactured, global::System.Int32 status)
        {
            FinishedProduct finishedProduct = new FinishedProduct();
            finishedProduct.ID = id;
            finishedProduct.DateManufactured = dateManufactured;
            finishedProduct.Status = status;
            return finishedProduct;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateManufactured
        {
            get
            {
                return _DateManufactured;
            }
            set
            {
                OnDateManufacturedChanging(value);
                ReportPropertyChanging("DateManufactured");
                _DateManufactured = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateManufactured");
                OnDateManufacturedChanged();
            }
        }
        private global::System.DateTime _DateManufactured;
        partial void OnDateManufacturedChanging(global::System.DateTime value);
        partial void OnDateManufacturedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EPC
        {
            get
            {
                return _EPC;
            }
            set
            {
                OnEPCChanging(value);
                ReportPropertyChanging("EPC");
                _EPC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EPC");
                OnEPCChanged();
            }
        }
        private global::System.String _EPC;
        partial void OnEPCChanging(global::System.String value);
        partial void OnEPCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AntennaObject_ID
        {
            get
            {
                return _AntennaObject_ID;
            }
            set
            {
                OnAntennaObject_IDChanging(value);
                ReportPropertyChanging("AntennaObject_ID");
                _AntennaObject_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AntennaObject_ID");
                OnAntennaObject_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _AntennaObject_ID;
        partial void OnAntennaObject_IDChanging(Nullable<global::System.Int32> value);
        partial void OnAntennaObject_IDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_FinishedProducts_dbo_AntennaObjects_AntennaObject_ID", "AntennaObjects")]
        public AntennaObject AntennaObject
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AntennaObject>("WMSwithRFID.WMScontextModel.FK_dbo_FinishedProducts_dbo_AntennaObjects_AntennaObject_ID", "AntennaObjects").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AntennaObject>("WMSwithRFID.WMScontextModel.FK_dbo_FinishedProducts_dbo_AntennaObjects_AntennaObject_ID", "AntennaObjects").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AntennaObject> AntennaObjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AntennaObject>("WMSwithRFID.WMScontextModel.FK_dbo_FinishedProducts_dbo_AntennaObjects_AntennaObject_ID", "AntennaObjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AntennaObject>("WMSwithRFID.WMScontextModel.FK_dbo_FinishedProducts_dbo_AntennaObjects_AntennaObject_ID", "AntennaObjects", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WMSwithRFID.WMScontextModel", Name="Manufacturer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Manufacturer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Manufacturer object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Manufacturer CreateManufacturer(global::System.Int32 id)
        {
            Manufacturer manufacturer = new Manufacturer();
            manufacturer.ID = id;
            return manufacturer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_ReaderObjects_dbo_Manufacturers_Manufacturer_ID", "ReaderObjects")]
        public EntityCollection<ReaderObject> ReaderObjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReaderObject>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_Manufacturers_Manufacturer_ID", "ReaderObjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReaderObject>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_Manufacturers_Manufacturer_ID", "ReaderObjects", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WMSwithRFID.WMScontextModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="weight">Initial value of the Weight property.</param>
        /// <param name="daysToExpire">Initial value of the DaysToExpire property.</param>
        /// <param name="unitPrice">Initial value of the UnitPrice property.</param>
        /// <param name="lastUpdate">Initial value of the LastUpdate property.</param>
        public static Product CreateProduct(global::System.Int32 id, global::System.Int32 weight, global::System.Int32 daysToExpire, global::System.Double unitPrice, global::System.DateTime lastUpdate)
        {
            Product product = new Product();
            product.ID = id;
            product.Weight = weight;
            product.DaysToExpire = daysToExpire;
            product.UnitPrice = unitPrice;
            product.LastUpdate = lastUpdate;
            return product;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private global::System.Int32 _Weight;
        partial void OnWeightChanging(global::System.Int32 value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DaysToExpire
        {
            get
            {
                return _DaysToExpire;
            }
            set
            {
                OnDaysToExpireChanging(value);
                ReportPropertyChanging("DaysToExpire");
                _DaysToExpire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DaysToExpire");
                OnDaysToExpireChanged();
            }
        }
        private global::System.Int32 _DaysToExpire;
        partial void OnDaysToExpireChanging(global::System.Int32 value);
        partial void OnDaysToExpireChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double UnitPrice
        {
            get
            {
                return _UnitPrice;
            }
            set
            {
                OnUnitPriceChanging(value);
                ReportPropertyChanging("UnitPrice");
                _UnitPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitPrice");
                OnUnitPriceChanged();
            }
        }
        private global::System.Double _UnitPrice;
        partial void OnUnitPriceChanging(global::System.Double value);
        partial void OnUnitPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdate
        {
            get
            {
                return _LastUpdate;
            }
            set
            {
                OnLastUpdateChanging(value);
                ReportPropertyChanging("LastUpdate");
                _LastUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdate");
                OnLastUpdateChanged();
            }
        }
        private global::System.DateTime _LastUpdate;
        partial void OnLastUpdateChanging(global::System.DateTime value);
        partial void OnLastUpdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Type_ID
        {
            get
            {
                return _Type_ID;
            }
            set
            {
                OnType_IDChanging(value);
                ReportPropertyChanging("Type_ID");
                _Type_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type_ID");
                OnType_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Type_ID;
        partial void OnType_IDChanging(Nullable<global::System.Int32> value);
        partial void OnType_IDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_AntennaObjects_dbo_Products_Product_ID", "AntennaObjects")]
        public EntityCollection<AntennaObject> AntennaObjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AntennaObject>("WMSwithRFID.WMScontextModel.FK_dbo_AntennaObjects_dbo_Products_Product_ID", "AntennaObjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AntennaObject>("WMSwithRFID.WMScontextModel.FK_dbo_AntennaObjects_dbo_Products_Product_ID", "AntennaObjects", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_Products_dbo_ProductTypes_Type_ID", "ProductTypes")]
        public ProductType ProductType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProductType>("WMSwithRFID.WMScontextModel.FK_dbo_Products_dbo_ProductTypes_Type_ID", "ProductTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProductType>("WMSwithRFID.WMScontextModel.FK_dbo_Products_dbo_ProductTypes_Type_ID", "ProductTypes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ProductType> ProductTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProductType>("WMSwithRFID.WMScontextModel.FK_dbo_Products_dbo_ProductTypes_Type_ID", "ProductTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ProductType>("WMSwithRFID.WMScontextModel.FK_dbo_Products_dbo_ProductTypes_Type_ID", "ProductTypes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WMSwithRFID.WMScontextModel", Name="ProductType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductType object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static ProductType CreateProductType(global::System.Int32 id)
        {
            ProductType productType = new ProductType();
            productType.ID = id;
            return productType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_Products_dbo_ProductTypes_Type_ID", "Products")]
        public EntityCollection<Product> Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product>("WMSwithRFID.WMScontextModel.FK_dbo_Products_dbo_ProductTypes_Type_ID", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product>("WMSwithRFID.WMScontextModel.FK_dbo_Products_dbo_ProductTypes_Type_ID", "Products", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WMSwithRFID.WMScontextModel", Name="ReaderObject")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReaderObject : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReaderObject object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static ReaderObject CreateReaderObject(global::System.Int32 id)
        {
            ReaderObject readerObject = new ReaderObject();
            readerObject.ID = id;
            return readerObject;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMPort
        {
            get
            {
                return _COMPort;
            }
            set
            {
                OnCOMPortChanging(value);
                ReportPropertyChanging("COMPort");
                _COMPort = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COMPort");
                OnCOMPortChanged();
            }
        }
        private global::System.String _COMPort;
        partial void OnCOMPortChanging(global::System.String value);
        partial void OnCOMPortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Antenna_ID
        {
            get
            {
                return _Antenna_ID;
            }
            set
            {
                OnAntenna_IDChanging(value);
                ReportPropertyChanging("Antenna_ID");
                _Antenna_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Antenna_ID");
                OnAntenna_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Antenna_ID;
        partial void OnAntenna_IDChanging(Nullable<global::System.Int32> value);
        partial void OnAntenna_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Manufacturer_ID
        {
            get
            {
                return _Manufacturer_ID;
            }
            set
            {
                OnManufacturer_IDChanging(value);
                ReportPropertyChanging("Manufacturer_ID");
                _Manufacturer_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Manufacturer_ID");
                OnManufacturer_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Manufacturer_ID;
        partial void OnManufacturer_IDChanging(Nullable<global::System.Int32> value);
        partial void OnManufacturer_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Warehouse_ID
        {
            get
            {
                return _Warehouse_ID;
            }
            set
            {
                OnWarehouse_IDChanging(value);
                ReportPropertyChanging("Warehouse_ID");
                _Warehouse_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Warehouse_ID");
                OnWarehouse_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Warehouse_ID;
        partial void OnWarehouse_IDChanging(Nullable<global::System.Int32> value);
        partial void OnWarehouse_IDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_ReaderObjects_dbo_AntennaObjects_Antenna_ID", "AntennaObjects")]
        public AntennaObject AntennaObject
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AntennaObject>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_AntennaObjects_Antenna_ID", "AntennaObjects").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AntennaObject>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_AntennaObjects_Antenna_ID", "AntennaObjects").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AntennaObject> AntennaObjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AntennaObject>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_AntennaObjects_Antenna_ID", "AntennaObjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AntennaObject>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_AntennaObjects_Antenna_ID", "AntennaObjects", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_ReaderObjects_dbo_Manufacturers_Manufacturer_ID", "Manufacturers")]
        public Manufacturer Manufacturer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Manufacturer>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_Manufacturers_Manufacturer_ID", "Manufacturers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Manufacturer>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_Manufacturers_Manufacturer_ID", "Manufacturers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Manufacturer> ManufacturerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Manufacturer>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_Manufacturers_Manufacturer_ID", "Manufacturers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Manufacturer>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_Manufacturers_Manufacturer_ID", "Manufacturers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_ReaderObjects_dbo_Warehouses_Warehouse_ID", "Warehouses")]
        public Warehouse Warehouse
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Warehouse>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_Warehouses_Warehouse_ID", "Warehouses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Warehouse>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_Warehouses_Warehouse_ID", "Warehouses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Warehouse> WarehouseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Warehouse>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_Warehouses_Warehouse_ID", "Warehouses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Warehouse>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_Warehouses_Warehouse_ID", "Warehouses", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WMSwithRFID.WMScontextModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="accountType">Initial value of the AccountType property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.Int32 accountType)
        {
            User user = new User();
            user.ID = id;
            user.AccountType = accountType;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AccountType
        {
            get
            {
                return _AccountType;
            }
            set
            {
                OnAccountTypeChanging(value);
                ReportPropertyChanging("AccountType");
                _AccountType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccountType");
                OnAccountTypeChanged();
            }
        }
        private global::System.Int32 _AccountType;
        partial void OnAccountTypeChanging(global::System.Int32 value);
        partial void OnAccountTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyPosition
        {
            get
            {
                return _CompanyPosition;
            }
            set
            {
                OnCompanyPositionChanging(value);
                ReportPropertyChanging("CompanyPosition");
                _CompanyPosition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyPosition");
                OnCompanyPositionChanged();
            }
        }
        private global::System.String _CompanyPosition;
        partial void OnCompanyPositionChanging(global::System.String value);
        partial void OnCompanyPositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Suffix
        {
            get
            {
                return _Suffix;
            }
            set
            {
                OnSuffixChanging(value);
                ReportPropertyChanging("Suffix");
                _Suffix = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Suffix");
                OnSuffixChanged();
            }
        }
        private global::System.String _Suffix;
        partial void OnSuffixChanging(global::System.String value);
        partial void OnSuffixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactNumber
        {
            get
            {
                return _ContactNumber;
            }
            set
            {
                OnContactNumberChanging(value);
                ReportPropertyChanging("ContactNumber");
                _ContactNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactNumber");
                OnContactNumberChanged();
            }
        }
        private global::System.String _ContactNumber;
        partial void OnContactNumberChanging(global::System.String value);
        partial void OnContactNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WMSwithRFID.WMScontextModel", Name="Warehouse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Warehouse : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Warehouse object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Warehouse CreateWarehouse(global::System.Int32 id)
        {
            Warehouse warehouse = new Warehouse();
            warehouse.ID = id;
            return warehouse;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WMSwithRFID.WMScontextModel", "FK_dbo_ReaderObjects_dbo_Warehouses_Warehouse_ID", "ReaderObjects")]
        public EntityCollection<ReaderObject> ReaderObjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReaderObject>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_Warehouses_Warehouse_ID", "ReaderObjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReaderObject>("WMSwithRFID.WMScontextModel.FK_dbo_ReaderObjects_dbo_Warehouses_Warehouse_ID", "ReaderObjects", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
